# Generated by Django 5.1.3 on 2024-12-11 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('contact', models.BigIntegerField()),
                ('password', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='user_images/')),
            ],
        ),
    ]
