# Generated by Django 5.1.3 on 2024-12-25 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='SubCategories_image/')),
                ('title', models.CharField(max_length=300)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.categories')),
            ],
        ),
    ]
